bomb:
  delay: 5 # The number of seconds until the bomb explodes
  cost:
    enabled: true
    price: 0.0
  actions:
    dropped:
      - action: explode
        power: 5
      - action: command
        command: "say <bomber>'s bomb exploded"

    held:
      - action: message
        message: <bomber>'s bomb exploded on you!
      - action: damage
        power: 5
      - action: sound
        sound: explode
        volume: 10
        pitch: 1
      - action: damage
        power: 5

update:
  checkForUpdates: true
  autoInstallUpdates: true
