bomb:
  delay: 5 # The number of seconds until the bomb explodes
  actions:
    dropped:
      - action: explode
        power: 5
      - action: command
        command: "say <bomber>'s bomb exploded"
